import type { Metadata } from "next";
import "./globals.css";

import { headers } from "next/headers";
import ContextProvider from '@/context'

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers()
  const cookies = headersList.get('cookie')

  return (
    <html lang="en">
      <body className="roboto-font bg-black">
        <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  )
}