import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  team,
  analytics,
  children,
}: Readonly<{
  team: React.ReactNode;
  analytics: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="roboto-font">
        <AntdRegistry>
          <div className="container mx-auto">
            <div className="flex justify-center text-blue-500 gap-4 text-2xl font-bold mt-3">
              <Link href="/">Home</Link>
              <Link href="/visitors">Visitors</Link>
            </div>
            <div className="flex justify-center gap-4 text-2xl font-bold mt-3">
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
